defaults: &defaults
  line:
    end_point: 'https://trialbot-api.line.me'
    to_channel: 1383378250
    event_type: "138311608800106203"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
